# default configuration
baseURL = "https://mun.hwtech.club"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "WATTMUN"

# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"


# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 2

[[menu.main]]
URL = "pastevents"
name = "Past Events"
weight = 3

[[menu.main]]
URL = "upcomingevents"
name = "Upcoming Events"
weight = 3

[[menu.main]]
URL = "volunteer_work"
name = "Volunteer Work"
weight = 3

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5


# default parameters
[params]
home = "Home"
logo = "images/logo.png"
# theme color
theme_color = "black"
# contact info
phone = "+971 55 698 6401"
email = "steve.fruits@email.com"
address = "Heriot Watt, Academic City , Dubai, UAE"
# meta description
author = ""
description = "This is meta description"
# google analytics
google_analytics_id = "" # Your ID
# copyright
copyright = "Copyright &copy; 2020 a theme by [gethugothemes](https://gethugothemes.com) and powered by [Hw Tech Club](https://hwtech.club)"


# contact
[params.contact]
enable = true
form_action = "#" # contact form works with : https://formspree.io

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# social site
[[params.social]]
icon = "ti-facebook"
URL = "#"

[[params.social]]
icon = "ti-instagram"
URL = "#"
